# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Github\Trainer_GUI\resources\UI\Infomation_Page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from qfluentwidgets import BodyLabel, ComboBox, LineEdit, PasswordLineEdit, PlainTextEdit, PrimaryPushButton

class Ui_Information_Page(object):
    def setupUi(self, Information_Page):
        Information_Page.setObjectName("Information_Page")
        Information_Page.resize(800, 600)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Information_Page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(40, 70, 40, 30)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BodyLabel = BodyLabel(Information_Page)
        self.BodyLabel.setObjectName("BodyLabel")
        self.horizontalLayout.addWidget(self.BodyLabel)
        self.LineEdit = LineEdit(Information_Page)
        self.LineEdit.setObjectName("LineEdit")
        self.horizontalLayout.addWidget(self.LineEdit)
        self.BodyLabel_2 = BodyLabel(Information_Page)
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.horizontalLayout.addWidget(self.BodyLabel_2)
        self.PasswordLineEdit = PasswordLineEdit(Information_Page)
        self.PasswordLineEdit.setObjectName("PasswordLineEdit")
        self.horizontalLayout.addWidget(self.PasswordLineEdit)
        self.BodyLabel_3 = BodyLabel(Information_Page)
        self.BodyLabel_3.setObjectName("BodyLabel_3")
        self.horizontalLayout.addWidget(self.BodyLabel_3)
        self.ComboBox = ComboBox(Information_Page)
        self.ComboBox.setAutoDefault(False)
        self.ComboBox.setObjectName("ComboBox")
        self.horizontalLayout.addWidget(self.ComboBox)
        self.PrimaryPushButton = PrimaryPushButton(Information_Page)
        self.PrimaryPushButton.setObjectName("PrimaryPushButton")
        self.horizontalLayout.addWidget(self.PrimaryPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.results_info = PlainTextEdit(Information_Page)
        self.results_info.setEnabled(False)
        self.results_info.setObjectName("results_info")
        self.verticalLayout.addWidget(self.results_info)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Information_Page)
        QtCore.QMetaObject.connectSlotsByName(Information_Page)

    def retranslateUi(self, Information_Page):
        _translate = QtCore.QCoreApplication.translate
        Information_Page.setWindowTitle(_translate("Information_Page", "Form"))
        self.BodyLabel.setText(_translate("Information_Page", "User Name"))
        self.BodyLabel_2.setText(_translate("Information_Page", "Password"))
        self.BodyLabel_3.setText(_translate("Information_Page", "Node"))
        self.ComboBox.setText(_translate("Information_Page", "ALL"))
        self.ComboBox.addItems(["ALL", "GPU01", "GPU02", "GPU03", "GPU04", "GPU05", "GPU06"])
        self.PrimaryPushButton.setText(_translate("Information_Page", "TEST"))

