# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Github\Trainer_GUI\resources\UI\Setting_Page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Setting_Page(object):
    def setupUi(self, Setting_Page):
        Setting_Page.setObjectName("Setting_Page")
        Setting_Page.resize(800, 600)
        self.PushButton = PushButton(Setting_Page)
        self.PushButton.setGeometry(QtCore.QRect(310, 140, 102, 32))
        self.PushButton.setObjectName("PushButton")

        self.retranslateUi(Setting_Page)
        QtCore.QMetaObject.connectSlotsByName(Setting_Page)

    def retranslateUi(self, Setting_Page):
        _translate = QtCore.QCoreApplication.translate
        Setting_Page.setWindowTitle(_translate("Setting_Page", "Form"))
        self.PushButton.setText(_translate("Setting_Page", "Push button"))
from qfluentwidgets import PushButton
